name: Build .deb Package

on:
  push:
    branches:
      - main   # Cambia 'main' por 'master' si tu rama principal se llama así
  pull_request:
    branches:
      - main   # También puedes activar el flujo en pull requests

jobs:
  build:
    runs-on: ubuntu-latest  # Usamos Ubuntu como entorno para compilar el .deb

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Hacemos checkout del código fuente del repositorio

    - name: Set up environment
      run: |
        sudo apt update
        sudo apt install -y build-essential dpkg-dev fakeroot

    - name: Build .deb package
      run: |
        # Creamos el archivo .deb usando dpkg-buildpackage
        make deb
